let albums = [
  {
    title: `POX WAVЁ`,
    img: `assets/1.png`,
    author: `Og Buda`,
    year: `2023`,
    description: `На POX VAWË артист исследует новые направления и всё больше
                    погружается в стилистику футуристичного трэп-звучания.`,
    tracklist: [
      {
        title: `Порш (Porsche)`,
        author: `Og Buda`,
        time: `3:00`,
        src: `music/1.mp3`,
        isPlaying: false,
      },
      {
        title: `Искс`,
        author: `Og Buda`,
        time: `2:34`,
        src: `music/2.mp3`,
        isPlaying: false,
      },
      {
        title: `Ради`,
        author: `Og Buda`,
        time: `2:12`,
        src: `music/3.mp3`,
        isPlaying: false,
      },
      {
        title: `Привет`,
        author: `Og Buda`,
        time: `1:43`,
        src: `music/4.mp3`,
        isPlaying: false,
      },
      {
        title: `SG2`,
        author: `Og Buda feat. 4n Way`,
        time: `2:14`,
        src: `music/5.mp3`,
        isPlaying: false,
      },
    ],
  },
  {
    title: `FREERIO 2`,
    img: `assets/2.jpg`,
    author: `Og Buda`,
    year: `2022`,
    description: `Этот альбом посвящён Rio Da Young OG, американскому рэперу, который в 2021 году сел на 5 лет в тюрьму.`,
    tracklist: [
      {
        title: ` Ты думал я забросил?`,
        author: `Og Buda`,
        time: `0:57`,
        src: `music/6.mp3`,
        isPlaying: false,
      },
      {
        title: `Следующий`,
        author: `Og Buda`,
        time: `1:41`,
        src: `music/7.mp3`,
        isPlaying: false,
      },
      {
        title: ` Любознательность`,
        author: `Og Buda feat. Брутто`,
        time: `2:32`,
        src: `music/8.mp3`,
        isPlaying: false,
      },
      {
        title: ` Грязный`,
        author: `Og Buda feat. Scally Milano, 163ONMY...`,
        time: `2:10`,
        src: `music/9.mp3`,
        isPlaying: false,
      },
      {
        title: `Давно`,
        author: `Og Buda`,
        time: `2:31`,
        src: `music/10.mp3`,
        isPlaying: false,
      },
    ],
  },
  {
    title: `Dark Lane Demo Tapes`,
    img: `assets/3.png`,
    author: `Drake`,
    year: `2020`,
    description: `сборник из 14 треков, ранее светившихся в качестве самостоятельных синглов (вроде "War" и "Tossie Slide"), утекших в сеть или неопубликованных песен.`,
    tracklist: [
      {
        title: `Deep Pockets`,
        author: `Drake`,
        time: `3:42`,
        src: `music/11.mp3`,
        isPlaying: false,
      },
      {
        title: ` When To Say When`,
        author: `Drake`,
        time: `3:43`,
        src: `music/12.mp3`,
        isPlaying: false,
      },
      {
        title: `Chicago Freestyle`,
        author: `Drake, Giveon`,
        time: `3:40`,
        src: `music/13.mp3`,
        isPlaying: false,
      },
      {
        title: `Not You Too`,
        author: `Drake feat. Chris Brown`,
        time: `4:29`,
        src: `music/14.mp3`,
        isPlaying: false,
      },
      {
        title: `Toosie Slide`,
        author: `Drake`,
        time: `4:07`,
        src: `music/15.mp3`,
        isPlaying: false,
      },
    ],
  },
  {
    title: `Скучаю но работаю`,
    img: `assets/4.jpg`,
    author: `Og Buda`,
    year: `2023`,
    description: `Пятый полноформатный альбом в карьере Гриши, состоящий из треков о бывших возлюбленных и рэперской жизни.`,
    tracklist: [
      {
        title: `Сандэй Сервис`,
        author: `Og Buda`,
        time: `2:09`,
        src: `music/16.mp3`,
        isPlaying: false,
      },
      {
        title: `Для Тебя (Пусто)`,
        author: `Og Buda`,
        time: `2:16`,
        src: `music/17.mp3`,
        isPlaying: false,
      },
      {
        title: `Касание`,
        author: `Og Buda feat. MAYOT`,
        time: `2:40`,
        src: `music/18.mp3`,
        isPlaying: false,
      },
      {
        title: `Интересно`,
        author: `Og Buda, MAYOT`,
        time: `2:31`,
        src: `music/19.mp3`,
        isPlaying: false,
      },
      {
        title: `Сердце <3 Время `,
        author: `Og Buda`,
        time: `3:00`,
        src: `music/20.mp3`,
        isPlaying: false,
      },
    ],
  },
];
